block: zram: Fix compilation issues
While porting changes to 4.4, looks like some functionality lost
and causing below compilation issues if we try to enable ZRAM.

[1]
drivers/block/zram/zram_drv.c: In function 'zram_bvec_write':
drivers/block/zram/zram_drv.c:724:9: error: 'ALLOC_ERROR_LOG_RATE_MS' \
undeclared (first use in this function)
         ALLOC_ERROR_LOG_RATE_MS))
         ^
drivers/block/zram/zram_drv.c:724:9: note: each undeclared identifier \
is reported only once for each function it appears in
drivers/block/zram/zram_drv.c: In function 'zram_add':
drivers/block/zram/zram_drv.c:1239:34: error: 'struct zram' has no \
member named 'queue'
  __set_bit(QUEUE_FLAG_FAST, &zram->queue->queue_flags);
                                  ^
make[4]: *** [drivers/block/zram/zram_drv.o] Error 1
make[3]: *** [drivers/block/zram] Error 2
make[2]: *** [drivers/block] Error 2
make[1]: *** [drivers] Error 2

[2]
drivers/block/zram/zram_drv.c: In function 'zram_add':
drivers/block/zram/zram_drv.c:1241:34: error: 'struct zram' \
has no member named 'queue'
  __set_bit(QUEUE_FLAG_FAST, &zram->queue->queue_flags);
                                  ^
make[4]: *** [drivers/block/zram/zram_drv.o] Error 1
make[3]: *** [drivers/block/zram] Error 2
make[2]: *** [drivers/block] Error 2

CRs-Fixed: 1013947
Change-Id: I4f7944069306ba92e1fd82625bc15c7fa3bcdb0c
Signed-off-by: Satya Durga Srinivasu Prabhala <satyap@codeaurora.org>